ROTOGURU_DST_NAMES = {'Detroit Defense': 'Lions', 'New York G Defense': 'Giants', 'New York J Defense': 'Jets',
                      'Jacksonville Defense': 'Jaguars', 'Buffalo Defense': 'Bills', 'Seattle Defense': 'Seahawks',
                      'Denver Defense': 'Broncos', 'Indianapolis Defense': 'Colts', 'Tampa Bay Defense': 'Buccaneers',
                      'Arizona Defense': 'Cardinals', 'Green Bay Defense': 'Packers', 'Tennessee Defense': 'Titans',
                      'Cincinnati Defense': 'Bengals', 'San Francisco Defense': '49ers', 'New Orleans Defense': 'Saints',
                      'Washington Defense': 'Redskins', 'Oakland Defense': 'Raiders', 'Carolina Defense': 'Panthers',
                      'New England Defense': 'Patriots', 'Kansas City Defense': 'Chiefs', 'Minnesota Defense': 'Vikings',
                      'Chicago Defense': 'Bears', 'Pittsburgh Defense': 'Steelers', 'Philadelphia Defense': 'Eagles',
                      'San Diego Defense': 'Chargers', 'Miami Defense': 'Dolphins', 'Baltimore Defense': 'Ravens',
                      'Houston Defense': 'Texans', 'Dallas Defense': 'Cowboys', 'St. Louis Defense': 'Rams',
                      'Atlanta Defense': 'Falcons', 'Cleveland Defense': 'Browns'}

FANPROS_DST_NAMES = {'Detroit Lions': 'Lions', 'New York Giants': 'Giants', 'New York Jets': 'Jets',
                     'Jacksonville Jaguars': 'Jaguars', 'Buffalo Bills': 'Bills', 'Seattle Seahawks': 'Seahawks',
                     'Denver Broncos': 'Broncos', 'Indianapolis Colts': 'Colts', 'Tampa Bay Buccaneers': 'Buccaneers',
                     'Arizona Cardinals': 'Cardinals', 'Green Bay Packers': 'Packers', 'Tennessee Titans': 'Titans',
                     'Cincinnati Bengals': 'Bengals', 'San Francisco 49ers': '49ers', 'New Orleans Saints': 'Saints',
                     'Washington Redskins': 'Redskins', 'Oakland Raiders': 'Raiders', 'Carolina Panthers': 'Panthers',
                     'New England Patriots': 'Patriots', 'Kansas City Chiefs': 'Chiefs', 'Minnesota Vikings': 'Vikings',
                     'Chicago Bears': 'Bears', 'Pittsburgh Steelers': 'Steelers', 'Philadelphia Eagles': 'Eagles',
                     'San Diego Chargers': 'Chargers', 'Miami Dolphins': 'Dolphins', 'Baltimore Ravens': 'Ravens',
                     'Houston Texans': 'Texans', 'Dallas Cowboys': 'Cowboys', 'St. Louis Rams': 'Rams',
                     'Atlanta Falcons': 'Falcons', 'Cleveland Browns': 'Browns'}

FANPROS_DST_NAMES = {'Detroit Lions': 'Lions', 'New York Giants': 'Giants', 'New York Jets': 'Jets',
                     'Jacksonville Jaguars': 'Jaguars', 'Buffalo Bills': 'Bills', 'Seattle Seahawks': 'Seahawks',
                     'Denver Broncos': 'Broncos', 'Indianapolis Colts': 'Colts', 'Tampa Bay Buccaneers': 'Buccaneers',
                     'Arizona Cardinals': 'Cardinals', 'Green Bay Packers': 'Packers', 'Tennessee Titans': 'Titans',
                     'Cincinnati Bengals': 'Bengals', 'San Francisco 49ers': '49ers', 'New Orleans Saints': 'Saints',
                     'Washington Redskins': 'Redskins', 'Oakland Raiders': 'Raiders', 'Carolina Panthers': 'Panthers',
                     'New England Patriots': 'Patriots', 'Kansas City Chiefs': 'Chiefs', 'Minnesota Vikings': 'Vikings',
                     'Chicago Bears': 'Bears', 'Pittsburgh Steelers': 'Steelers', 'Philadelphia Eagles': 'Eagles',
                     'San Diego Chargers': 'Chargers', 'Miami Dolphins': 'Dolphins', 'Baltimore Ravens': 'Ravens',
                     'Houston Texans': 'Texans', 'Dallas Cowboys': 'Cowboys', 'St. Louis Rams': 'Rams',
                     'Atlanta Falcons': 'Falcons', 'Cleveland Browns': 'Browns'}

ABBREVIATIONS = {'Brooklyn Lions': 'BKL', 'Houston Oilers': 'HOO', 'Chicago Cardinals': 'CHC', 'Dallas Texans (1960-62)': 'DAT', 'Cincinnati Bengals': 'CIN', 'New York Giants': 'NYG', 'Los Angeles Buccaneers': 'LAB', 'St. Louis Gunners': 'SLG', 'New York Yanks': 'NYA', 'Miami Seahawks': 'MIS', 'Detroit Lions': 'DET', 'Chi Cardinals-Pit Steelers': 'CHP', 'New York Brickley Giants': 'NYI', 'Cleveland Indians': 'CLI', 'San Diego Chargers': 'SD', 'Baltimore Colts (1946-50)': 'BAO', 'Cincinnati Celts': 'CIC', 'New York Bulldogs': 'NYB', 'Boston Braves': 'BOB', 'Tennessee Titans': 'TEN', 'Chicago Bears': 'CHI', 'Akron Pros': 'AKR', 'Washington Senator': 'WSN', 'Buffalo Bisons (1946)': 'BUB', 'Cincinnati Reds': 'CIR', 'Green Bay Packers': 'GB', 'Los Angeles Raiders': 'LAI', 'Hartford Blues': 'HAR', 'New Orleans Saints': 'NO', 'Chicago Tigers': 'CHT', 'New England Patriots': 'NE', 'Frankford Yellow Jackets': 'FRA', 'Decatur Staleys': 'DEC', 'Tampa Bay Buccaneers': 'TB', 'Minneapolis Marines': 'MNM', 'Newark Tornadoes': 'NWK', 'Buffalo Bills': 'BUF', 'Tonawanda Kardex': 'TON', 'Columbus Tigers': 'COL', 'Carolina Panthers': 'CAR', 'Louisville Brecks': 'LOB', 'Brooklyn Dodgers (1946-48)': 'BKN', 'New York Yankees': 'NYK', 'Evansville Crimson Giants': 'EVA', 'New York Jets': 'NYJ', 'Providence Steam Roller': 'PRO', 'Akron Indians': 'AKI', 'Pittsburgh Pirates': 'PIP', 'Boston Patriots': 'BOS', 'Staten Island Stapletons': 'SIS', 'Kenosha Maroons': 'KEN', 'Minnesota Vikings': 'MIN', 'Dallas Cowboys': 'DAL', 'Buffalo Bisons (1927, 29)': 'BUN', 'Hammond Pros': 'HAM', 'Philadelphia Eagles': 'PHI', 'St. Louis Rams': 'STL', 'Pottsville Maroons': 'POT', 'Buffalo All-Americans': 'BUA', 'Bkn Tigers-Bos Yanks': 'BKB', 'Boston Yanks': 'BOY', 'Detroit Heralds': 'DTH', 'Denver Broncos': 'DEN', 'Cleveland Rams': 'CLR', 'Tennessee Oilers': 'TNO', 'Los Angeles Dons': 'LAD', 'Boston Bulldogs': 'BOD', 'Toledo Maroons': 'TOL', 'Rock Island Independents': 'RII', 'Racine Legion': 'RAL', 'Cleveland Bulldogs': 'CLB', 'Canton Bulldogs': 'CAN', 'Muncie Flyers': 'MUN', 'Louisville Colonels': 'LOC', 'Indianapolis Colts': 'IND', 'Seattle Seahawks': 'SEA', 'Arizona Cardinals': 'ARI', 'Chicago Hornets': 'CHH', 'Houston Texans': 'HOU', 'Minneapolis Red Jackets': 'MNR', 'Jacksonville Jaguars': 'JAC', 'Baltimore Colts': 'BAC', 'Boston Redskins': 'BOR', 'Detroit Tigers': 'DTG', 'Baltimore Ravens': 'BAL', 'St. Louis Cardinals': 'SLC', 'Chicago Staleys': 'CHS', 'Milwaukee Badgers': 'MIL', 'Pittsburgh Steelers': 'PIT', 'Racine Tornadoes': 'RAT', 'Brooklyn Tigers': 'BKT', 'Rochester Jeffersons': 'ROC', 'Buffalo Bills (1947-49)': 'BUL', 'Cleveland Browns': 'CLE', 'Los Angeles Chargers': 'LAC', 'Oakland Raiders': 'OAK', 'Dayton Triangles': 'DAY', 'Oorang Indians': 'OOR', 'Detroit Panthers': 'DTP', 'Phi Eagles-Pit Steelers': 'PHP', 'St. Louis All-Stars': 'SLA', 'Atlanta Falcons': 'ATL', 'Brooklyn Dodgers (1930-43)': 'BKD', 'Chicago Rockets': 'CHR', 'Dallas Texans (1952)': 'DAX', 'Orange Tornadoes': 'ORG', 'Cleveland Tigers': 'CLT', 'Phoenix Cardinals': 'PHX', 'San Francisco 49ers': 'SF', 'Portsmouth Spartans': 'POR', 'Duluth Eskimos': 'DUE', 'Washington Redskins': 'WAS', 'Buffalo Rangers': 'BUR', 'Kansas City Cowboys': 'KC', 'Duluth Kelleys': 'DUK', 'Los Angeles Rams': 'LAM', 'Miami Dolphins': 'MIA', 'Detroit Wolverines': 'DTW', 'Kansas City Chiefs': 'KC', 'Columbus Panhandles': 'COP', 'New York Titans': 'NYT', 'Buffalo Bisons (1924-25)': 'BUS'}

DK_TO_PD = {'Ari': 'ARI',
'Atl': 'ATL',
'Bal': 'BAL',
'Car': 'CAR',
'Chi': 'CHC',
'Cin': 'CIN',
'Dal': 'DAL',
'Den': 'DEN',
'Det': 'DET',
'GB': 'GB',
'Hou': 'HOU',
'Ind': 'IND',
'KC': 'KC',
'Mia': 'MIA',
'Min': 'MIN',
'NYJ': 'NYJ',
'Oak': 'OAK',
'Phi': 'PHI',
'SD': 'SD',
'Sea': 'SEA',
'SF': 'SF',
'StL': 'STL',
'TB': 'TB',
'Was' : 'WAS',
'NE': 'NE'
}